spring:
  profiles:
    active: dev
  application:
    name: LibraryManagementProject
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 86400000 # 24 hours
    refresh-expiration-ms: 604800000 # 7 days
  mail:
    from: noreply@librarymanagement.com
  library:
    fine-per-day: 1.50
    max-borrow-days:
      STUDENT: 14
      FACULTY: 30
      LIBRARIAN: 21
      ADMIN: 30
    max-borrow-books:
      STUDENT: 5
      FACULTY: 10
      LIBRARIAN: 5
      ADMIN: 10
